// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRManager.Infrastructure.Data;

#nullable disable

namespace PRManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201114539_AddSecretPasswordToConfig")]
    partial class AddSecretPasswordToConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PRManager.Domain.Models.AutomationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitlabToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutomationConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(9020),
                            GithubToken = "",
                            GitlabToken = "",
                            SecretPassword = "",
                            UpdatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(9020)
                        });
                });

            modelBuilder.Entity("PRManager.Domain.Models.PullRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeployedToStg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeployedToStgAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitlabIssueLink")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsCorrection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PipelineLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReqVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rollback")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamsLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VersionBatchRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionGroupStatus")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VersionRequested")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("DevId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("SprintId");

                    b.HasIndex("VersionBatchRefId");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("PRManager.Domain.Models.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("PRManager.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubTokenEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitLabTokenEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(8890),
                            Email = "rodrigo.barbosa@company.com",
                            Name = "Rodrigo Barbosa",
                            PasswordHash = "$2a$11$XZvCfQqmJQZJZQZJZQZJZu7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(8890),
                            Email = "itallo.cerqueira@company.com",
                            Name = "Itallo Cerqueira",
                            PasswordHash = "$2a$11$XZvCfQqmJQZJZQZJZQZJZu7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(8890),
                            Email = "marcos.paulo@company.com",
                            Name = "Marcos Paulo",
                            PasswordHash = "$2a$11$XZvCfQqmJQZJZQZJZQZJZu7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(8890),
                            Email = "samuel.santos@company.com",
                            Name = "Samuel Santos",
                            PasswordHash = "$2a$11$XZvCfQqmJQZJZQZJZQZJZu7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7",
                            Role = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 1, 11, 45, 39, 329, DateTimeKind.Utc).AddTicks(8890),
                            Email = "kemilly.alvez@company.com",
                            Name = "Kemilly Alvez",
                            PasswordHash = "$2a$11$XZvCfQqmJQZJZQZJZQZJZu7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7Z7",
                            Role = 2
                        });
                });

            modelBuilder.Entity("PRManager.Domain.Models.VersionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitlabIssueLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rollback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("SprintId");

                    b.ToTable("VersionBatches");
                });

            modelBuilder.Entity("PRManager.Domain.Models.PullRequest", b =>
                {
                    b.HasOne("PRManager.Domain.Models.User", "ApprovedBy")
                        .WithMany("ApprovedPullRequests")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRManager.Domain.Models.User", "Dev")
                        .WithMany("PullRequests")
                        .HasForeignKey("DevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRManager.Domain.Models.Sprint", "Sprint")
                        .WithMany("PullRequests")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PRManager.Domain.Models.VersionBatch", "VersionBatchRef")
                        .WithMany("PullRequests")
                        .HasForeignKey("VersionBatchRefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");

                    b.Navigation("Dev");

                    b.Navigation("Sprint");

                    b.Navigation("VersionBatchRef");
                });

            modelBuilder.Entity("PRManager.Domain.Models.VersionBatch", b =>
                {
                    b.HasOne("PRManager.Domain.Models.Sprint", "Sprint")
                        .WithMany("VersionBatches")
                        .HasForeignKey("SprintId");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("PRManager.Domain.Models.Sprint", b =>
                {
                    b.Navigation("PullRequests");

                    b.Navigation("VersionBatches");
                });

            modelBuilder.Entity("PRManager.Domain.Models.User", b =>
                {
                    b.Navigation("ApprovedPullRequests");

                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("PRManager.Domain.Models.VersionBatch", b =>
                {
                    b.Navigation("PullRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
